[build]
builder = "nixpacks"

[deploy]
startCommand = "python start.py"
healthcheckPath = "/health"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"

[env]
ENVIRONMENT = "production"
PYTHONPATH = "."
HF_HOME = "/tmp/hf_cache"
